-- Consulta simple para una tabla 

/* Entrega el nombre y la edad dentro de un rango entre 2000 y 2015*/

SELECT NAME, YEAR  FROM MOVIES WHERE YEAR >= 2000 AND YEAR <= 2015;

SELECT NAME, YEAR  FROM MOVIES WHERE YEAR BETWEEN 2000 and 2015;

/* Entrega todas las columnas que tengas un ranking entre 3 y 6 o
la calificacion perfecta*/

SELECT * FROM MOVIES WHERE RANK>3 AND RANK<6 or RANK IN (9,9.9);

SELECT * FROM MOVIES WHERE RANK>3 AND RANK<6 or RANK=9 OR RANK=9.9;

/* Entrega el nombre y el año donde sean distinto del 2010*/

SELECT NAME, YEAR FROM MOVIES WHERE YEAR != 2010;

SELECT NAME, YEAR FROM MOVIES WHERE NOT YEAR = 2010;


/* Entrega el nombre del actor completo y el rankin mayor a 5 */ 

SELECT ACTORS.FIRST_NAME,ACTORS.LAST_NAME,MOVIES.RANK FROM ACTORS, ROLES, MOVIES
WHERE ACTORS.ID = ROLES.ACTOR_ID AND ROLES.MOVIE_ID = MOVIES.ID AND MOVIES.RANK > 5;


SELECT ACTORS.FIRST_NAME,ACTORS.LAST_NAME,MOVIES.RANK FROM ACTORS INNER JOIN ROLES ON ACTORS.ID = ROLES.ACTOR_ID INNER JOIN MOVIES ON ROLES.MOVIE_ID = MOVIES.ID WHERE MOVIES.RANK > 5;

/* Actor que ha participado en más películas */

select a.first_name, a.last_name, count(*) as num_movies from actors a, roles r where a.id =
    r.actor_id group by a.first_name, a.last_name order by num_movies desc;


select a.first_name, a.last_name, count(*) as num_movies from actors a join roles r on a.id = r.actor_id group by a.first_name, a.last_name order by num_movies desc;

/* Entrega el actor que su nombre comience con J uniendo 3 tablas*/

SELECT MOVIES.NAME, ACTORS.FIRST_NAME, ACTORS.LAST_NAME FROM MOVIES JOIN ROLES ON MOVIES.ID = ROLES.MOVIE_ID JOIN ACTORS ON ROLES.ACTOR_ID = ACTORS.ID WHERE ACTORS.FIRST_NAME  LIKE 'J%';

SELECT MOVIES.NAME, ACTORS.FIRST_NAME, ACTORS.LAST_NAME FROM MOVIES, ROLES, ACTORS WHERE MOVIES.ID = ROLES.MOVIE_ID AND ROLES.ACTOR_ID = ACTORS.ID AND ACTORS.FIRST_NAME LIKE 'J%';



/* MOSTRAR LA CANTIDAD DE ACTORES QUE CUENTA CADA PELICULA DONDE TAMBIEN ME MUESTRE EL DIRECTOR  */

SELECT MOVIES.NAME, DIRECTORS.FIRST_NAME, DIRECTORS.LAST_NAME, COUNT(*) CANTIDAD_ACTORES FROM MOVIES
    JOIN ROLES ON MOVIES.ID = ROLES.MOVIE_ID
    JOIN ACTORS ON ROLES.ACTOR_ID = ACTORS.ID
    JOIN MOVIES_DIRECTORS ON MOVIES.ID = MOVIES_DIRECTORS.MOVIE_ID
    JOIN DIRECTORS ON MOVIES_DIRECTORS.DIRECTOR_ID = DIRECTORS.ID
            GROUP BY MOVIES.NAME, DIRECTORS.FIRST_NAME, DIRECTORS.LAST_NAME HAVING COUNT(*) > 1;

SELECT MOVIES.NAME, DIRECTORS.FIRST_NAME, DIRECTORS.LAST_NAME, COUNT(*) CANTIDAD_ACTORES FROM MOVIES, ROLES, ACTORS, MOVIES_DIRECTORS, DIRECTORS
    WHERE MOVIES.ID = ROLES.MOVIE_ID AND ROLES.ACTOR_ID = ACTORS.ID AND MOVIES.ID = MOVIES_DIRECTORS.MOVIE_ID AND MOVIES_DIRECTORS.DIRECTOR_ID = DIRECTORS.ID
    GROUP BY MOVIES.NAME, DIRECTORS.FIRST_NAME, DIRECTORS.LAST_NAME HAVING COUNT(*) > 1;

/* AGRUPAR LA CANTIDAD DE PELICULAS DEL MISMO GENERO */

SELECT MOVIES_GENRES.GENRE, COUNT(*) CANTIDAD FROM MOVIES_GENRES
    JOIN MOVIES ON MOVIES_GENRES.MOVIE_ID = MOVIES.ID
        GROUP BY MOVIES_GENRES.GENRE;

SELECT MOVIES_GENRES.GENRE, COUNT(*) CANTIDAD FROM MOVIES_GENRES, MOVIES
    WHERE MOVIES_GENRES.MOVIE_ID = MOVIES.ID
        GROUP BY MOVIES_GENRES.GENRE;

/* MOSTRAR EL NOMBRE DEL DIRECTOR QUE A DIRIGIDO MAS DE UNA PELICULA ENTREGANDO ASI EL NOMBRE DE LA PELICULA */

SELECT DIRECTORS.FIRST_NAME, DIRECTORS.LASt_NAME, MOVIES.NAME FROM DIRECTORS, MOVIES_DIRECTORS, MOVIES
    WHERE DIRECTORS.ID = MOVIES_DIRECTORS.DIRECTOR_ID AND MOVIES_DIRECTORS.MOVIE_ID = MOVIES.ID
        AND MOVIES.ID IN (SELECT MOVIES_DIRECTORS.MOVIE_ID FROM MOVIES_DIRECTORS GROUP BY MOVIES_DIRECTORS.MOVIE_ID HAVING COUNT(*) > 1);

SELECT DIRECTORS.FIRST_NAME, DIRECTORS.LAST_NAME, MOVIES.NAME FROM DIRECTORS
    JOIN MOVIES_DIRECTORS ON DIRECTORS.ID = MOVIES_DIRECTORS.DIRECTOR_ID
    JOIN MOVIES ON MOVIES_DIRECTORS.MOVIE_ID = MOVIES.ID
        WHERE MOVIES.ID IN (SELECT MOVIES_DIRECTORS.MOVIE_ID FROM MOVIES_DIRECTORS GROUP BY MOVIES_DIRECTORS.MOVIE_ID HAVING COUNT(*) > 1);

/* Obtener el genero de peliculas que mas actores femeninos (F) */

select g.genre, count(*) as cantidad_Actoras
from MOVIES_GENRES g,
     ROLES r,
     ACTORS a
where g.MOVIE_ID = r.MOVIE_ID
  and r.ACTOR_ID = a.ID
  and a.GENDER = 'F'
group by g.genre having count(*) = (select max(count)
from (select g.genre, count(*) as count from MOVIES_GENRES g,
                              ROLES r,
                              ACTORS a
  where g.MOVIE_ID = r.MOVIE_ID and r.ACTOR_ID = a.ID and a.GENDER = 'F' group by g.genre));


select * from (select g.genre, count(*) as cantidad_Actoras
from MOVIES_GENRES g join ROLES r on g.MOVIE_ID = r.MOVIE_ID
join ACTORS a on r.ACTOR_ID = a.ID
where a.GENDER = 'F' group by g.genre
order by cantidad_Actoras desc) where ROWNUM < 2;


